USE [master]
GO

/****** Object:  Database [HotelReservierung]    Script Date: 23.03.2023 16:00:59 ******/
CREATE DATABASE [HotelReservierung]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HotelReservierung', FILENAME = N'C:\SQL-Kurs\99-HotelReservierung\HotelReservierung.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'HotelReservierung_log', FILENAME = N'C:\SQL-Kurs\99-HotelReservierung\HotelReservierung_Log.ldf' , SIZE = 9024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HotelReservierung].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HotelReservierung] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HotelReservierung] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HotelReservierung] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HotelReservierung] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HotelReservierung] SET ARITHABORT OFF 
GO

ALTER DATABASE [HotelReservierung] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HotelReservierung] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HotelReservierung] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HotelReservierung] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HotelReservierung] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HotelReservierung] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HotelReservierung] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HotelReservierung] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HotelReservierung] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HotelReservierung] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HotelReservierung] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HotelReservierung] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HotelReservierung] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HotelReservierung] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HotelReservierung] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HotelReservierung] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HotelReservierung] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HotelReservierung] SET RECOVERY FULL 
GO

ALTER DATABASE [HotelReservierung] SET  MULTI_USER 
GO

ALTER DATABASE [HotelReservierung] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HotelReservierung] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HotelReservierung] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HotelReservierung] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HotelReservierung] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HotelReservierung] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HotelReservierung] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HotelReservierung] SET  READ_WRITE 
GO


